<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE  CNVs[
<!ELEMENT CNVs (CNV+)> <!--abstracts -->
<!ELEMENT CNV (name,builds,human,mouse,zfish)>
<!ELEMENT  builds (hsap_build,mmusculus_build,drerio_build)>
<!ELEMENT human (chrom,minimum,maximum,phenotype)>
<!ELEMENT minimum (segment)>
<!ELEMENT maximum (segment)>
<!-- Note the genes listed under maximum are in addition to those in minimum -->
<!ELEMENT segment (start,end,(gene+))>
<!ELEMENT mouse ((gene+),phenotype)>
<!ELEMENT zfish ((gene+),EQ)>
<!ELEMENT gene (symbol, entrezID)>
<!ELEMENT phenotype (term+)>
<!ELEMENT EQ (E,Q)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT chrom (#PCDATA)>
<!ELEMENT start (#PCDATA)>
<!ELEMENT end (#PCDATA)>
<!ELEMENT symbol (#PCDATA)>
<!ELEMENT entrezID (#PCDATA)>
<!ELEMENT hsap_build (#PCDATA)>
<!ELEMENT mmusculus_build (#PCDATA)>
<!ELEMENT drerio_build (#PCDATA)>
<!ELEMENT term (#PCDATA)>
<!ELEMENT E (#PCDATA)>
<!ELEMENT Q (#PCDATA)>
<!ATTLIST CNV  type  (deletion | duplication) #REQUIRED >
<!ATTLIST CNV  type  (minimum | maximum ) #REQUIRED >
]>

<CNVs>
    <CNV type="deletion">
        <name>Williams Beuren syndrome (WBS)</name>
        <builds>
            <hsap_build>hg18</hsap_build>
            <mmusculus_build>?</mmusculus_build>
            <drerio_build>?</drerio_build>
        </builds>
        
        <human>
            <chrom>7</chrom>
            <minimum>
                <segment>
                    <start>71970679</start>
                    <end>74254837</end>
                    <gene>
                        <symbol>CLIP2</symbol>
                        <entrezID>7461</entrezID>
                    </gene>
                </segment>
            </minimum>
            <maximum>
                <segment>
                    <start></start>
                    <end></end>
                    <gene>
                        <symbol></symbol>
                        <entrezID></entrezID>
                    </gene>
                </segment>
            </maximum>
            <phenotype>
                <term>HP:0000006</term>
                <term>HP:0000010</term>
                <term>HP:0000015</term>
            </phenotype>
        </human>
        
        <mouse>
            <gene>
                <symbol>Clip2</symbol>
                <entrezID>269713</entrezID>
            </gene>
            <phenotype>
                <term></term>
            </phenotype>
        </mouse>
        <zfish>
            <gene>
                <symbol>LOC556406 CAP-Gly domain-containing linker protein 2-like</symbol>
                <entrezID>556406</entrezID>
            </gene>
            <EQ>
                <E></E>
                <Q></Q>
            </EQ>
        </zfish>
    </CNV>
</CNVs>
